version: "3.8"
services:
  db:
    image: mysql:8
    container_name: poc-mysql
    ports:
      - "3306:3306"
    volumes:
      - poc-mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

volumes:
  poc-mysql: {}